apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: write-pods
  namespace: default
subjects:
  - kind: ServiceAccount
    name: app-sa
roleRef:
  kind: Role
  name: pod-creater
  apiGroup: rbac.authorization.k8s.io