apiVersion: v1
kind: Pod
metadata:
  name: apache
  namespace: application
  labels:
    env: development
    tier: frontend
    app: apache
spec:
  containers:
    - name: apache
      image: paketobuildpacks/httpd:0.7
      ports:
        - containerPort: 80
          protocol: TCP