apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: backend
spec:
  selector:
    app: mysql   # must match the label on your db Pod
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  type: ClusterIP
